### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by ThomasTheHedgehog** [ClusterM/coolboy-multirom-builder#1]
C:\Users\Thomas\Desktop\NES\Multirom\coolboy-multirom-builder>tools\TilesConverter.exe menu.png menu_pattern0.dat menu_nametable0.dat menu_palette0.dat
'tools\TilesConverter.exe' is not recognized as an internal or external command,
operable program or batch file.
Oops, something is wrong!
Press any key to continue . . .

**Comment by ClusterM** [comment]
Hi.
Do you have this file actually?

**Comment by ClusterM** [comment]
Okay...
