### ISSUE TITLE
Reset emulation

### ISSUE THREAD

**Issue by RetHunter3000** [ClusterM/coolboy-multirom-builder#2]
Алексей, если сделаешь сохранение курсора, сделай пожалуйста эмуляцию ресет.
Чтобы при включении стартовала первая игра, а при сбросе автоматом включалась следущая. Грубо говоря чтобы меню не рисовалось и само включало игру и переставляло курсор на следущую.
Спасибо!

**Comment by ClusterM** [comment]
Сохранение курсора есть, когда картридж поддерживает запись. Не думаю, что это многим нужно, можно сделать как опцию.

**Comment by ClusterM** [comment]
Сделано.
