### ISSUE TITLE
Error: Unknowm mapper #7 for Battletoads    в Cluster.Famicom.Program.Main(String[] args)

### ISSUE THREAD

**Issue by alexandrage** [ClusterM/coolboy-multirom-builder#3]
Error: Unknowm mapper #7 for Battletoads    в Cluster.Famicom.Program.Main(String[] args)

**Comment by the-jet** [comment]
Battletoads не будет работать на картриджах Coolboy или Mindkinds. Поддерживаются только мапперы NROM #0 и MMC3 #4, а тут AxROM #7. Насколько помню, конвертаций в MMC3 нет, т.к. игра весьма сложно устроена, в том числе из-за простейшего железа картриджа. У Battletoads переключаются сразу 32кб, а в MMC3 можно переключать только два окна по 8кб, а последнее фиксировано. Плюс, там отличается мирроринг - из-за этого нельзя будет отображать панель жизней и сам игровой процесс одновременно. Поэтому и нет MMC-хака. Так что проще будет купить готовый китайский картридж с игрой, либо тот же Coolgirl.

Другой вопрос, что можно поправить опечатку в тексте ошибки) Может, речь и была об этом?

**Comment by alexandrage** [comment]
I wanted to merge the game for the emulator

**Comment by lass222** [comment]
> Battletoads не будет работать на картриджах Coolboy или Mindkinds. Поддерживаются только мапперы NROM #0 и MMC3 [#4](https://github.com/ClusterM/coolboy-multirom-builder/issues/4), а тут AxROM [#7](https://github.com/ClusterM/coolboy-multirom-builder/issues/7). Насколько помню, конвертаций в MMC3 нет, т.к. игра весьма сложно устроена, в том числе из-за простейшего железа картриджа. У Battletoads переключаются сразу 32кб, а в MMC3 можно переключать только два окна по 8кб, а последнее фиксировано. Плюс, там отличается мирроринг - из-за этого нельзя будет отображать панель жизней и сам игровой процесс одновременно. Поэтому и нет MMC-хака. Так что проще будет купить готовый китайский картридж с игрой, либо тот же Coolgirl.
> 
> Другой вопрос, что можно поправить опечатку в тексте ошибки) Может, речь и была об этом?

А что скажете по хаку Mario Rider, тоже не могу собрать, не понимает маппер, можно ли конвертировать в подходящий маппер?

**Comment by ClusterM** [comment]
> А что скажете по хаку Mario Rider, тоже не могу собрать, не понимает маппер, можно ли конвертировать в подходящий маппер?

Нет, там всё очень сложно и есть функционал, который MMC3 не умеет.
