### ISSUE TITLE
"Не собирается"

### ISSUE THREAD

**Issue by RafGul** [ClusterM/coolboy-multirom-builder#5]
Здравствуйте! При запуске "!build_rom.bat" в coolboy-multirom-builder для создания ROM'а, вылазит ошибка:
![1](https://user-images.githubusercontent.com/98255257/151666890-dd05f045-93df-4cac-ba9c-828b5f964f69.jpg)
[Kabuki_-_Quantum_Fighter(Hack).zip](https://github.com/ClusterM/coolboy-multirom-builder/files/7964003/Kabuki_-_Quantum_Fighter.Hack.zip)

**Comment by the-jet** [comment]
Ошибки в софте тут нет, тут явно написано, какая ошибка. Он обнаружил в заголовке РОМа 4-screen mirroring, а такие игры на MMC3 не идут. Можно только vertical и horizontal. Проблема в роме. Приложенный файл - шедевровский перевод с двумя неправильными байтами, один из них в заголовке. Используйте корректную версию.

```
Search for differences

1. C:\Users\me\Desktop\Kabuki_-_Quantum_Fighter(Hack).nes: 262 160 bytes
2. C:\Users\me\Desktop\Kabuki - Quantum Fighter (U) [T+Rus_Shedevr].nes: 262 160 bytes
Offsets: hexadec.

    6:	49	40
1BC0F:	0F	0A

2 difference(s) found. 
```
